version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - "POSTGRES_DB=tickers"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration:
    build: ./db
    container_name: db-migration
    environment:
      - "PGUSER=postgres"
      - "PGPASSWORD=postgres"
      - "PGHOST=postgres-db"
      - "PGPORT=5432"
      - "PGDATABASE=tickers"
    depends_on:
      - db

  api:
    container_name: api
    build:
      context: ./api
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=tickers
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    ports:
      - "8080:8080"

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
