CREATE SCHEMA IF NOT EXISTS tickers;

CREATE TABLE tickers.entries (
  id BIGSERIAL PRIMARY KEY,
  amount TEXT NOT NULL,
  currency_pair TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
