version: "3.8"

services:
  # Category Tree Consumer - Database
  db:
    image: postgres:latest
    container_name: db
    environment:
      - "POSTGRES_DB=tickers"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  # Category Tree Consumer - Database Migration
  db-migration:
    container_name: db-migration
    build:
      context: ./db/
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/tickers
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_SCHEMAS=something
      - FLYWAY_TABLE=schema_version
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
    depends_on:
      - db
    command: migrate
